# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_bm_rust_wrappers", use_symbols = TRUE, package_name = "bm.rust")

#' @usage NULL
#' @useDynLib bm.rust, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

brownian_bridge <- function(x, y, s, t, times) .Call(wrap__brownian_bridge, x, y, s, t, times)


# nolint end
