# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pseudo_fusion_wrappers", use_symbols = TRUE, package_name = "pseudo.fusion")

#' @docType package
#' @usage NULL
#' @useDynLib pseudo.fusion, .registration = TRUE
NULL

mixture_fusion_example <- function(burn, ss, num_is) .Call(wrap__mixture_fusion_example, burn, ss, num_is)


# nolint end
