[package]
name = 'apt_rust'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'apt_rust'

[dependencies]
array-init = "2.1.0"
extendr-api = '*'
indicatif = "0.17.8"
rand = "0.8.5"
rand_distr = "0.4.3"
