# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_apt_rust_wrappers", use_symbols = TRUE, package_name = "apt.rust")

#' @docType package
#' @usage NULL
#' @useDynLib apt.rust, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

apt <- function(burn, ss, adapt) .Call(wrap__apt, burn, ss, adapt)


# nolint end
