# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_cts_smc_wrappers", use_symbols = TRUE, package_name = "cts.smc")

#' @usage NULL
#' @useDynLib cts.smc, .registration = TRUE
NULL

cts_smc_rust <- function(ss, target_time) .Call(wrap__cts_smc_rust, ss, target_time)

path_smc_rust <- function(n, n_steps, tt, sample_t) .Call(wrap__path_smc_rust, n, n_steps, tt, sample_t)

euler_approx_rust <- function(ss, target_time, n_intervals) .Call(wrap__euler_approx_rust, ss, target_time, n_intervals)

brownian_motion_fpt <- function(n) .Call(wrap__brownian_motion_fpt, n)

brownian_motion_fpt2 <- function(n) .Call(wrap__brownian_motion_fpt2, n)

algo5 <- function(x_start, x_end, t_start, t_end, t_sim) .Call(wrap__algo5, x_start, x_end, t_start, t_end, t_sim)

a6 <- function(x, y, s, t, theta, x_start, u) .Call(wrap__a6, x, y, s, t, theta, x_start, u)


# nolint end
